**Curso: Ciencia de Datos e Introducción al Machine Learning**

**Práctica de laboratorio: No. 3**

**Título de la Práctica: Programación Orientada a Objetos y Preprocesamiento de Datos**

**Docente: M.Sc. Geiner Giovanny Barbosa Casanova**

**Semestre: 2026 - II**

# Introducción

La presente práctica de laboratorio articula los fundamentos de la **Programación Orientada a Objetos (POO)** con las técnicas de preprocesamiento de datos, dos pilares esenciales en el desarrollo de sistemas de ingeniería modernos. En la primera parte, se aborda la abstracción conceptual de componentes de hardware y sistemas de medición, modelando su comportamiento y propiedades mediante estructuras de software reutilizables (clases y objetos). En la segunda parte, se emplea el ecosistema científico de ***Python*** para el tratamiento de datos crudos. Esto incluye la mitigación de fallos de telemetría (datos faltantes), la transformación de señales cualitativas (codificación) y la estandarización matemática de magnitudes físicas (escalado), con el fin de acondicionar la información para la futura implementación de algoritmos de **Machine Learning**.

# Objetivos

*   Modelar sistemas físicos y dispositivos de medición aplicando los principios de la Programación Orientada a Objetos.
*   Integrar el ecosistema de librerías científicas para la importación, inspección exploratoria y manipulación estructurada de conjuntos de datos provenientes de archivos CSV.

*   Aplicar técnicas de preprocesamiento de datos para limpiar y transformar registros de ingeniería, ejecutando métodos de eliminación, imputación, codificación de variables categóricas y escalado de características numéricas.

# Programación Orientada a Objetos en Python


En el ámbito de la **Ingeniería Electrónica** y la instrumentación, la Programación Orientada a Objetos (POO) constituye un paradigma diseñado para estructurar el código mediante la agrupación de datos y comportamientos relacionados. Este enfoque permite modelar sistemas físicos —como arreglos de sensores, instrumentos de medición o redes de microcontroladores— utilizando arquitecturas modulares, lo que garantiza la mantenibilidad de sistemas complejos. Los siguientes conceptos son fundamentales en la POO:

* **Clase:** representa la plantilla abstracta que define las propiedades estructurales y funcionales de un sistema (por ejemplo, la hoja de datos genérica de un osciloscopio).

* **Objeto e Instancia:** un objeto es la entidad concreta construida en la memoria a partir de una clase. El proceso de crear una instancia de una clase se denomina instanciación.

* **Atributos:** variables encapsuladas dentro del objeto que almacenan su estado físico o configuración actual (por ejemplo, la tasa de baudios de un puerto serial).

* **Métodos:** funciones definidas dentro de una clase que representan operaciones o comportamientos que pueden ser ejecutados por sus objetos (por ejemplo, un objeto que represente un sensor podría disponer de un método para realizar una lectura o actualizar su valor medido).

Fuente:
* Ramalho, L. (2021). Fluent Python: Clear, Concise, and Effective Programming (2nd ed.). O'Reilly Media.

## Componentes Clave de la Estructura de una Clase

Para comprender la sintaxis de la Programación Orientada a Objetos en Python, es imperativo definir dos elementos exclusivos de su arquitectura interna:

* **El método `__init__` (Constructor):** Es una función especial reservada por Python que se ejecuta de manera automática en el instante exacto en que se instancia (crea) un nuevo objeto. Su propósito exclusivo es inicializar el estado del componente, asignando los valores de arranque a sus atributos.

* **El parámetro `self`:** En ***Python***, **self** representa la instancia específica que se está manipulando en la memoria. Dado que una misma clase puede usarse para crear cientos de componentes distintos, **self** garantiza que, al modificar el valor de un objeto, no se alteren los valores de los demás. Se debe incluir siempre como el primer parámetro en la definición de cualquier método dentro de la clase.

Fuente:

* Matthes, E. (2023). Python Crash Course: A Hands-On, Project-Based Introduction to Programming (3rd ed.). No Starch Press.

### Ejemplo 1:

In [ ]:
# 1. Definición de la Clase
class Resistencia:
    # Método constructor: Define e inicializa los atributos del objeto
    def __init__(self, nombre: str, resistencia_ohmios: float):
        # Atributos de instancia
        self.nombre = nombre
        self.resistencia_ohmios = resistencia_ohmios

    # Método para calcular el voltaje según la Ley de Ohm (V = I * R)
    def calcular_voltaje(self, corriente_amperios: float):
        voltaje = corriente_amperios * self.resistencia_ohmios
        return voltaje

In [ ]:
# 2. Instanciación: Se crean dos objetos independientes en memoria
resistencia_pullup = Resistencia(nombre="R1_PullUp", resistencia_ohmios=10000.0) # 10 kΩ
resistencia_limitadora = Resistencia(nombre="R2_LED", resistencia_ohmios=220.0)    # 220 Ω

In [ ]:
# 3. Acceso a Atributos e Invocación de Métodos
corriente_test = 0.015 # 15 mA

# Cálculo de caída de voltaje para R2_LED
v_led = resistencia_limitadora.calcular_voltaje(corriente_test)

print(f"Componente: {resistencia_limitadora.nombre}")
print(f"Valor: {resistencia_limitadora.resistencia_ohmios} Ohmios")
print(f"Caída de voltaje a {corriente_test} A: {v_led:.2f} Voltios")

### Ejemplo 2:

In [ ]:
# 1. Definición de la Clase (Plantilla para un Sensor de Temperatura)
# La clase define los atributos y comportamientos
# que tendrán los objetos de este tipo.

class SensorTemperaturaIoT:
    # Método constructor: Se ejecuta automáticamente al instanciar el objeto
    def __init__(self, id_sensor: str, ubicacion: str, rango_max_c: float):
        # Atributos de instancia
        self.id_sensor = id_sensor
        self.ubicacion = ubicacion
        self.rango_max_c = rango_max_c
        # Estado inicial del sensor.
        self.estado_activo = True
        # Lista utilizada para almacenar las lecturas.
        self.historial_lecturas = []

    # Método de instancia para simular la toma de datos
    def registrar_lectura(self, valor_celsius: float):
        # Verificación del estado del sensor.
        if not self.estado_activo:
            print(f"Error: El sensor {self.id_sensor} está desactivado.")
            return
        # Verificación del límite máximo.
        if valor_celsius > self.rango_max_c:
            print(f"¡ALERTA! Lectura {valor_celsius}°C supera el límite de {self.rango_max_c}°C en {self.ubicacion}.")

        # Almacenamiento de la lectura.
        self.historial_lecturas.append(valor_celsius)
        print(f"[{self.id_sensor}] Lectura registrada: {valor_celsius}°C")

    # Método para obtener el promedio de lecturas
    def calcular_promedio(self) -> float:
    # Verificación de la existencia de lecturas.
        if not self.historial_lecturas:
            return 0.0
        # Cálculo del promedio.
        return sum(self.historial_lecturas) / len(self.historial_lecturas)

In [ ]:
# 2. Instanciación de Objetos
sensor_foso = SensorTemperaturaIoT(id_sensor="SENS-01", ubicacion="Cuarto de Transformadores", rango_max_c=75.0)
sensor_ambiente = SensorTemperaturaIoT(id_sensor="SENS-02", ubicacion="Laboratorio de Microelectrónica", rango_max_c=35.0)

In [ ]:
# 3. Uso de Métodos y Atributos
print("Operación del Sistema de Telemetría")
sensor_foso.registrar_lectura(68.2)
sensor_foso.registrar_lectura(78.5) # Dispara alerta
sensor_ambiente.registrar_lectura(24.1)

print(f"\nPromedio del {sensor_foso.id_sensor}: {sensor_foso.calcular_promedio():.2f}°C")

### Actividades POO

1. Definir una clase llamada `Resistencia` con los atributos `valor_ohmios` y `tolerancia_pct`. Instanciar una resistencia de $220\ \Omega$ al $5\%$.
2. Agregar a la clase `Resistencia` un método llamado `obtener_descripcion()` que imprima el valor y la tolerancia en un formato legible
3. Crear una clase llamada `Bateria` con atributos `capacidad_mah` y `voltaje_nominal`. Incluir un método que calcule y retorne la energía total almacenada en Wh ($Wh = \frac{mAh \cdot V}{1000}$).
4. Diseñar una clase `Multimetro` que almacene un listado de mediciones de voltaje. Incluir un método `agregar_medicion(v)` que ignore valores negativos e imprima un mensaje de advertencia.
5. Crear la clase `PanelSolar` con atributos para `superficie_m2` y `eficiencia_pct`. Desarrollar un método `generar_potencia(irradiancia_w_m2)` que calcule la potencia de salida en vatios ($P = A \cdot E \cdot \eta$, donde $\eta = \text{eficiencia} / 100$) y registre un historial de potencia generada.

# Uso de Librerías y el Ecosistema Científico

En el desarrollo de software y la ciencia de datos, rara vez se construyen sistemas complejos partiendo desde cero. Una librería (o biblioteca) es un conjunto de módulos precompilados que contienen clases, funciones y métodos estructurados para resolver problemas específicos. Al importar una librería, el usuario adquiere la capacidad de instanciar objetos y utilizar herramientas matemáticas altamente optimizadas sin necesidad de redactar el código subyacente.

En el ecosistema científico de ***Python***, el flujo de trabajo estándar en ingeniería se fundamenta en la integración de librerías especializadas:

**NumPy:** proporciona los objetos base (`ndarrays`) para cálculos matriciales y operaciones de álgebra lineal con alta eficiencia computacional, superando las limitaciones de rendimiento de las listas nativas de Python.

**Pandas:** construida sobre NumPy, introduce la clase `DataFrame`, una estructura bidimensional diseñada para la manipulación, alineación y limpieza de registros tabulares y series de tiempo.

**Matplotlib:** librería fundamental para la renderización de gráficos y la exploración visual de datos físicos, permitiendo el trazado de señales y la identificación visual de anomalías.

Fuente:

* Matthes, E. (2023). Python Crash Course: A Hands-On, Project-Based Introduction to Programming (3rd ed.). No Starch Press

# Preprocesamiento y Preparación de Datos

El preprocesamiento de datos consiste en transformar registros sin tratar (provenientes de conversores ADC, buses SPI/I2C, archivos log, entre otros) en un formato matricial apto para algoritmos de **Machine Learning**. Esta fase implica procesos como:


* **Tratamiento de Faltantes:** la pérdida de paquetes en telemetría requiere la aplicación de estrategias estadísticas rigurosas. Esto abarca desde la eliminación estricta (descarte de registros corruptos) hasta la imputación estadística (estimación de valores mediante medidas de tendencia central o interpolación para series temporales).

* **Codificación de Categóricos:** los algoritmos operan exclusivamente con tensores numéricos. Por tanto, el texto debe ser mapeado a enteros (codificación ordinal para jerarquías) o a vectores binarios (codificación one-hot para variables nominales independientes) con el fin de evitar la inducción de falsas relaciones algebraicas.

* **Escalado de Características:** la estandarización de las variables a una distribución normal (transformación Z) previene que magnitudes físicas inherentemente altas (como la velocidad en RPM) dominen el cálculo de distancias matemáticas frente a variables críticas de menor magnitud (como las vibraciones en milímetros por segundo).

Fuentes:

* McKinney, W. (2022). Python for Data Analysis: Data Wrangling with pandas, NumPy, and Jupyter (3rd ed.). O'Reilly Media.

* Géron, A. (2022). Hands-On Machine Learning with Scikit-Learn, Keras, and TensorFlow (3rd ed.). O'Reilly Media.

## Funciones para el Tratamiento de Datos Faltantes

Cuando se trabaja con conjuntos de datos provenientes de dispositivos electrónicos o sensores de campo, es común encontrar registros incompletos representados por el valor NaN (Not a Number). Las herramientas de pandas y scikit-learn ofrecen funciones específicas para su gestión:

* **df.dropna():** descarta del DataFrame las filas o columnas que contengan uno o más valores NaN. Se utiliza cuando la cantidad de datos perdidos es mínima y no compromete el tamaño de la muestra.
* **df.fillna():** reemplaza directamente los valores `NaN` con un valor fijo especificado por el usuario (por ejemplo, reemplazar lecturas nulas con $0$).
* **df.interpolate():** realiza una estimación matemática para llenar los vacíos evaluando los puntos adyacentes. El parámetro `method='linear'` calcula una recta entre la lectura anterior y la posterior, lo cual es ideal para series temporales continuas de sensores.
* **SimpleImputer(strategy=...):** clase de `scikit-learn` diseñada para automatizar el reemplazo de valores nulos. Mediante el parámetro strategy, permite seleccionar el criterio de imputación: `'mean'` (media aritmética), `'median'` (mediana) o `'most_frequent'` (moda).

Fuentes:

* McKinney, W. (2022). Python for Data Analysis: Data Wrangling with pandas, NumPy, and Jupyter (3rd ed.). O'Reilly Media.

* Pedregosa, F., et al. (2011). Scikit-learn: Machine Learning in Python. Journal of Machine Learning Research, 12, 2825-2830.

### Ejemplo 3:

In [ ]:
import pandas as pd
import numpy as np
from sklearn.impute import SimpleImputer

# Se genera un conjunto de datos simplificado con lecturas de un sensor de temperatura
datos_sensor = {
    "Tiempo_s": [0, 1, 2, 3, 4],
    "Temperatura_C": [22.1, np.nan, 22.8, np.nan, 23.5]
}
df_temp = pd.DataFrame(datos_sensor)

print("Datos Originales con NaN")
display(df_temp)

Datos Originales con NaN

   Tiempo_s  Temperatura_C
0         0           22.1
1         1            NaN
2         2           22.8
3         3            NaN
4         4           23.5

In [ ]:
# Opción A: Interpolación lineal (recomendada para señales continuas)
df_interpolado = df_temp.copy()
df_interpolado["Temperatura_C"] = df_interpolado["Temperatura_C"].interpolate(method='linear')

print("Resultado con interpolate()")
display(df_interpolado)

Resultado con interpolate()

   Tiempo_s  Temperatura_C
0         0          22.10
1         1          22.45
2         2          22.80
3         3          23.15
4         4          23.50

In [ ]:
# Opción B: Imputación con la media mediante SimpleImputer
imputador = SimpleImputer(strategy='mean')
df_imputado = df_temp.copy()
df_imputado[["Temperatura_C"]] = imputador.fit_transform(df_temp[["Temperatura_C"]])

print("\nResultado con SimpleImputer(strategy='mean')")
display(df_imputado)

Resultado con SimpleImputer(strategy='mean')

   Tiempo_s  Temperatura_C
0         0           22.1
1         1           22.8
2         2           22.8
3         3           22.8
4         4           23.5

## Funciones para la Codificación de Variables Categóricas

Los modelos matemáticos requieren entradas exclusivamente numéricas. La transformación de variables cualitativas (texto) se realiza mediante dos herramientas principales:

* **OrdinalEncoder():** clase de `scikit-learn` utilizada cuando las categorías poseen un orden o jerarquía física clara (por ejemplo: Nivel de Batería: Bajo < Medio < Alto). A través del argumento `categories`, se define explícitamente la secuencia deseada para asignar enteros consecutivos ($0, 1, 2, \dots$).
* **pd.get_dummies():** función de `pandas` empleada para la codificación One-Hot. Convierte cada categoría independiente de una columna nominal (sin orden implícito, como tipos de sensores o protocolos) en una nueva columna binaria compuesta exclusivamente por ceros ($0$) y unos ($1$).

Fuentes:

* McKinney, W. (2022). Python for Data Analysis: Data Wrangling with pandas, NumPy, and Jupyter (3rd ed.). O'Reilly Media.

* Pedregosa, F., et al. (2011). Scikit-learn: Machine Learning in Python. Journal of Machine Learning Research, 12, 2825-2830.

### Ejemplo 4:

In [6]:

import pandas as pd
from sklearn.preprocessing import OrdinalEncoder

# Se genera un DataFrame con datos categóricos de dispositivos IoT
datos_iot = {
    "ID_Dispositivo": ["DEV-01", "DEV-02", "DEV-03", "DEV-04"],
    "Nivel_Alarma": ["Bajo", "Alto", "Medio", "Bajo"], # Variable Ordinal (Tiene orden)
    "Interfaz": ["I2C", "SPI", "I2C", "UART"]         # Variable Nominal (Sin orden)
}
df_iot = pd.DataFrame(datos_iot)

print("Datos Categóricos Originales")
display(df_iot)

Datos Categóricos Originales

  ID_Dispositivo Nivel_Alarma Interfaz
0         DEV-01         Bajo      I2C
1         DEV-02         Alto      SPI
2         DEV-03        Medio      I2C
3         DEV-04         Bajo     UART

In [ ]:
# 1. Codificación Ordinal para 'Nivel_Alarma'
# Se define el orden lógico: Bajo (0) -> Medio (1) -> Alto (2)
orden_prioridad = [["Bajo", "Medio", "Alto"]]
encoder = OrdinalEncoder(categories=orden_prioridad)

df_iot["Alarma_Codigo"] = encoder.fit_transform(df_iot[["Nivel_Alarma"]])

In [ ]:
# 2. Codificación One-Hot para 'Interfaz' mediante pd.get_dummies()
df_final = pd.get_dummies(df_iot, columns=["Interfaz"], dtype=int)

print("\nResultado tras Codificación")
display(df_final)

Resultado tras Codificación

,ID_Dispositivo,Nivel_Alarma,Alarma_Codigo,Interfaz_I2C,Interfaz_SPI,Interfaz_UART
0,DEV-01,Bajo,0.0,1,0,0
1,DEV-02,Alto,2.0,0,1,0
2,DEV-03,Medio,1.0,1,0,0
3,DEV-04,Bajo,0.0,0,0,1

### Actividades Preprocesamiento y Preparación de Datos

1. Cargar un archivo CSV mediante una URL pública usando Pandas e imprimir las primeras 3 filas con `.head(3)`. ✅

2. Identificar la cantidad de valores nulos por columna en el DataFrame cargado utilizando los métodos `.isna()`.sum() `Código en línea`. ✅

3. Aplicar interpolación lineal a una columna con valores nulos que represente una señal de temperatura en el tiempo.

4. Aplicar codificación One-Hot a una variable categórica de marcas de microcontroladores (`["Microchip"`, `"STMicroelectronics"`, `"Texas Instruments"`]).

5. Cargar un conjunto de datos, imputar los valores faltantes continuos con la mediana, codificar una variable de severidad de falla ([`"Leve"`, `"Moderada"`, `"Crítica"`]) mediante `OrdinalEncoder` y estandarizar todas las variables numéricas finales con `StandardScaler`.